### ISSUE TITLE
Api: are all our methods which can be const appropriately const?

### ISSUE THREAD

**Issue by baconpaul** [baconpaul/tipsy-encoder#11]
Subject says it all

**Comment by Paul-Dempsey** [comment]
We've mostly transferring value types (bytes and floats), where constness doesn't matter, but it's worth looking at where we're taking pointers, where it does matter.

**Comment by baconpaul** [comment]
Yeah also if someone does use this with const .& semantics it would be nice 

constexpr would be better but that sorta requires c++ 20 for constexpr variable unions. 

My latest pr does best we can and need with c++11 so based on your review and subsequent merge of #12 I propose we close this
